// webapp-angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { HttpClient } from '@angular/common/http';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {

  constructor(
    private http: HttpClient
  ) {

  }

  getDjango(): void {
    this.http.get('http://localhost:8000/polls')
    .subscribe(response => {
      console.log(response);
    });
  }

  getFlask(): void {
    this.http.get('http://localhost:8888/polls')
    .subscribe(response => {
      console.log(response);
    });
  }

  getExpress(): void {
    this.http.get('http://localhost:3000')
    .subscribe(response => {
      console.log(response);
    });
  }

  getNestJs(): void {
    this.http.get('http://localhost:3001')
    .subscribe(response => {
      console.log(response);
    });
  }
}

<p>
  <button (click)="getDjango()">Get Django</button>
</p>
<p>
  <button (click)="getFlask()">Get Flask</button>
</p>
<p>
  <button (click)="getExpress()">Get Express</button>
</p>
<p>
  <button (click)="getNestJs()">Get NestJs</button>
</p>

// webapp-react/src/components/App.jsx
import React from 'react';
import '../styles/components/App.styl';

const App = () => {

  const getDjango = async () => {
    const request = await fetch('http://localhost:8000/polls');
    const data = await request.json();
    console.log(data);
  }

  const getFlask = async () => {
    const request = await fetch('http://localhost:8888/polls');
    const data = await request.json();
    console.log(data);
  }

  const getExpress = async () => {
    const request = await fetch('http://localhost:3000');
    const data = await request.json();
    console.log(data);
  }

  const getNestJs = async () => {
    const request = await fetch('http://localhost:3001');
    const data = await request.json();
    console.log(data);
  }

  return (
    <div>
      <p>
        <button onClick={getDjango}>Get Django</button>
      </p>
      <p>
        <button onClick={getFlask}>Get Flask</button>
      </p>
      <p>
        <button onClick={getExpress}>Get Express</button>
      </p>
      <p>
        <button onClick={getNestJs}>Get NestJs</button>
      </p>
    </div>
  )
};

export default App;
